// Namentlicher Bestand aller neuen Hotels.
//
// Wird gebraucht, BEVOR die Katalogtexte geschrieben sind: Fuer einen
// Aussenansichts-Prompt reichen Ziel, Charakter und Ordnername. Dadurch kann
// die Bildgeneration parallel zur Katalogarbeit laufen.
//
// ACHTUNG: Die Namen sind ab jetzt fest. Der Ordnername leitet sich daraus ab
// (hotels/h30-vale-dourado/2.png) - eine spaetere Umbenennung wuerde die
// bereits erzeugten Bilder von ihrem Haus trennen.

export const ROSTER = [
  // --- Algarve -----------------------------------------------------------
  { id: "h30", ziel: "algarve", name: "Vale Dourado", kat: "luxus", sterne: 5,
    bau: "low white luxury hotel wings following the edge of a golden sandstone cliff, deep terraces, flat roofs",
    ort: "above a cove on the Algarve coast in Portugal, ochre cliffs and pine umbrellas", licht: "warm late afternoon light in early autumn" },
  { id: "h31", ziel: "algarve", name: "Casa das Amendoeiras", kat: "boutique", sterne: 4,
    bau: "small whitewashed Portuguese country house hotel with a blue-painted trim and a single storey wing",
    ort: "in a quiet inland Algarve village surrounded by almond trees", licht: "clear spring morning, almond trees in blossom" },
  { id: "h32", ziel: "algarve", name: "Praia Larga Resort", kat: "familie", sterne: 4,
    bau: "wide four-storey family resort with stepped balconies and awnings, painted sand and white",
    ort: "behind a long dune beach on the eastern Algarve", licht: "bright midday summer sun" },
  { id: "h33", ziel: "algarve", name: "Pensão Marisol", kat: "budget", sterne: 2,
    bau: "plain two-storey guesthouse with a tiled facade and small iron balconies",
    ort: "in a narrow street of a Portuguese fishing town, two blocks from the harbour", licht: "flat overcast light, late autumn" },
  { id: "h34", ziel: "algarve", name: "Miradouro Sagres", kat: "strand", sterne: 4,
    bau: "compact modern hotel of stacked white cubes with large glazed fronts",
    ort: "on an exposed clifftop at the south-western tip of Portugal, low windswept scrub", licht: "dramatic light before an autumn storm" },

  // --- Sardinien ---------------------------------------------------------
  { id: "h35", ziel: "sardinien", name: "Punta Granito", kat: "luxus", sterne: 5,
    bau: "luxury hotel of rough pink granite blocks, low and wide, half hidden by juniper",
    ort: "on a granite headland above a turquoise Sardinian bay", licht: "golden hour in June" },
  { id: "h36", ziel: "sardinien", name: "Stazzo Li Mari", kat: "finca", sterne: 4,
    bau: "converted Sardinian stone farmstead with thick walls, small windows and a courtyard arch",
    ort: "in the macchia hinterland of northern Sardinia, cork oaks around", licht: "hazy warm afternoon in September" },
  { id: "h37", ziel: "sardinien", name: "Hotel Cala Bianca", kat: "strand", sterne: 4,
    bau: "three-storey seaside hotel painted pale coral with deep shaded loggias",
    ort: "directly above a white sand cove on Sardinia", licht: "bright clear summer morning" },
  { id: "h38", ziel: "sardinien", name: "Corte Nuraghe", kat: "boutique", sterne: 3,
    bau: "small stone-built boutique hotel with a barrel-vaulted entrance and lime-washed walls",
    ort: "at the edge of an inland Sardinian village, dry stone walls and fig trees", licht: "soft evening light in late summer" },

  // --- Teneriffa ---------------------------------------------------------
  { id: "h39", ziel: "teneriffa", name: "Costa Volcán", kat: "strand", sterne: 4,
    bau: "long horizontal hotel building in dark volcanic stone and white render, wide sea-facing terraces",
    ort: "above a black lava beach on Tenerife, palm groves and the volcano behind", licht: "bright winter sun, deep blue sky" },
  { id: "h40", ziel: "teneriffa", name: "Jardín del Teide", kat: "luxus", sterne: 5,
    bau: "grand colonial-style luxury hotel with arcaded galleries and a red tiled roof",
    ort: "in subtropical gardens on Tenerife with the volcano peak in the far distance", licht: "warm January afternoon" },
  { id: "h41", ziel: "teneriffa", name: "Aparthotel Los Silos", kat: "apart", sterne: 3,
    bau: "simple four-storey apartment hotel, white with blue balcony railings, exterior stairs",
    ort: "in a quiet town on the north coast of Tenerife, banana plantations nearby", licht: "soft light under high winter cloud" },
  { id: "h42", ziel: "teneriffa", name: "Finca La Caldera", kat: "boutique", sterne: 4,
    bau: "restored Canarian manor house with dark carved wooden balconies and a lava stone base",
    ort: "on a terraced hillside in northern Tenerife, laurel forest above", licht: "morning light with mist over the ridge" },
  { id: "h43", ziel: "teneriffa", name: "Playa Sur Family", kat: "familie", sterne: 4,
    bau: "large family hotel complex in sand and terracotta tones with a curved balcony front",
    ort: "on the sunny south coast of Tenerife, palms and volcanic rock", licht: "hard midday sun in February" },

  // --- Barcelona ---------------------------------------------------------
  { id: "h44", ziel: "barcelona", name: "Eixample Gràcia", kat: "stadt", sterne: 4,
    bau: "elegant Modernisme corner building with wrought iron balconies and a rounded stone facade, hotel entrance under an awning",
    ort: "on a wide tree-lined avenue in Barcelona", licht: "clear spring morning" },
  { id: "h45", ziel: "barcelona", name: "Casa Ribera", kat: "boutique", sterne: 4,
    bau: "narrow restored townhouse with shuttered windows and a small stone portal",
    ort: "in a narrow lane of the Gothic quarter of Barcelona", licht: "shaded, warm reflected light at midday" },
  { id: "h46", ziel: "barcelona", name: "Gran Vía Palace", kat: "luxus", sterne: 5,
    bau: "monumental early twentieth century palace hotel with a stone facade, tall windows and a glazed rooftop pavilion",
    ort: "on a grand boulevard in Barcelona", licht: "blue hour, facade softly lit" },
  { id: "h47", ziel: "barcelona", name: "Hostal Poblenou", kat: "budget", sterne: 2,
    bau: "plain rendered four-storey guesthouse with simple windows and a small ground floor entrance",
    ort: "in a former industrial quarter of Barcelona, low workshops around", licht: "flat grey winter light" },
  { id: "h48", ziel: "barcelona", name: "Mar Bella Suites", kat: "apart", sterne: 3,
    bau: "modern apartment hotel with a rhythmic grid facade and recessed loggias",
    ort: "a few streets behind the city beach in Barcelona", licht: "bright autumn afternoon" },

  // --- Wien --------------------------------------------------------------
  { id: "h49", ziel: "wien", name: "Palais Lindengasse", kat: "luxus", sterne: 5,
    bau: "Viennese city palace with a pale stuccoed facade, tall arched windows and a carriage gate",
    ort: "in the inner districts of Vienna, bare plane trees along the street", licht: "cold clear December afternoon, thin snow on the pavement" },
  { id: "h50", ziel: "wien", name: "Hotel Ringblick", kat: "stadt", sterne: 4,
    bau: "solid Gründerzeit corner building, six storeys, ochre render with white window frames",
    ort: "on a boulevard in Vienna with tram tracks in the foreground", licht: "grey November light, wet asphalt" },
  { id: "h51", ziel: "wien", name: "Pension Josefstadt", kat: "budget", sterne: 2,
    bau: "modest four-storey Viennese apartment building with a simple street door",
    ort: "in a quiet residential street in Vienna", licht: "overcast late winter morning" },
  { id: "h52", ziel: "wien", name: "Boutiquehotel Naschmarkt", kat: "boutique", sterne: 4,
    bau: "slim restored townhouse with a green-painted ground floor and large first-floor windows",
    ort: "beside a covered market street in Vienna, empty stalls at dawn", licht: "early morning light in spring" },

  // --- Lissabon ----------------------------------------------------------
  { id: "h53", ziel: "lissabon", name: "Azulejo Alfama", kat: "boutique", sterne: 4,
    bau: "narrow Lisbon townhouse entirely faced in blue and white patterned tiles, iron balconies",
    ort: "in a steep alley in the Alfama district of Lisbon", licht: "warm side light in the late afternoon" },
  { id: "h54", ziel: "lissabon", name: "Miradouro Graça", kat: "stadt", sterne: 4,
    bau: "cream-rendered hotel building of five storeys with a rooftop terrace and pergola",
    ort: "on a hilltop in Lisbon overlooking terracotta roofs and the river", licht: "soft evening light in October" },
  { id: "h55", ziel: "lissabon", name: "Palácio Estrela", kat: "luxus", sterne: 5,
    bau: "eighteenth century palace with a pink lime-washed facade, stone window surrounds and a formal garden wall",
    ort: "in a leafy quarter of Lisbon, jacaranda trees in front", licht: "spring morning, jacarandas in bloom" },
  { id: "h56", ziel: "lissabon", name: "Baixa Studios", kat: "apart", sterne: 3,
    bau: "restored Pombaline block with regular windows and small juliet balconies, apartment hotel entrance",
    ort: "in the grid streets of downtown Lisbon", licht: "bright hard light at noon" },

  // --- Tirol -------------------------------------------------------------
  { id: "h57", ziel: "tirol", name: "Bergblick Sölden", kat: "berg", sterne: 4,
    bau: "large alpine hotel with a wide gabled roof, dark timber balconies on every floor and a white rendered base",
    ort: "at the foot of a Tyrolean ski slope, snow-covered spruce forest behind", licht: "bright winter day, deep snow, blue shadows" },
  { id: "h58", ziel: "tirol", name: "Alpenhof Zillertal", kat: "familie", sterne: 4,
    bau: "broad family hotel in traditional Tyrolean style with painted window surrounds and flower boxes",
    ort: "in a wide green Tyrolean valley with mountains behind", licht: "clear summer morning, meadows in flower" },
  { id: "h59", ziel: "tirol", name: "Chalet Hohe Munde", kat: "luxus", sterne: 5,
    bau: "modern luxury chalet hotel of aged timber and glass, low and horizontal, large panorama windows",
    ort: "on a snowy plateau above a Tyrolean valley", licht: "sunrise in January, pink light on the peaks" },
  { id: "h60", ziel: "tirol", name: "Gasthof Bergrast", kat: "budget", sterne: 2,
    bau: "simple village inn with a steep roof, whitewashed walls and a wooden first-floor balcony",
    ort: "in a small Tyrolean village street", licht: "grey light with fresh snow falling" },
  { id: "h61", ziel: "tirol", name: "Waldquelle Spa", kat: "boutique", sterne: 4,
    bau: "compact spa hotel clad in dark larch with a green roof, glazed wellness wing",
    ort: "at the edge of a Tyrolean forest, autumn larches turning gold", licht: "misty October morning" },

  // --- Südtirol ----------------------------------------------------------
  { id: "h62", ziel: "suedtirol", name: "Dolomiten Lodge", kat: "berg", sterne: 4,
    bau: "alpine lodge of stone base and timber upper floors, deep roof overhang, long balconies",
    ort: "below the pale rock walls of the Dolomites", licht: "cold clear winter afternoon, snowfields" },
  { id: "h63", ziel: "suedtirol", name: "Weingut Ansitz Prantl", kat: "finca", sterne: 4,
    bau: "South Tyrolean manor with a crenellated tower, thick plastered walls and arched windows",
    ort: "among vineyards on a South Tyrolean slope", licht: "warm October light, vine leaves red and gold" },
  { id: "h64", ziel: "suedtirol", name: "Hotel Rosengarten", kat: "luxus", sterne: 5,
    bau: "contemporary luxury hotel in pale stone and glass, cantilevered floors facing the mountains",
    ort: "on a meadow terrace facing the Dolomite peaks", licht: "alpenglow at dusk in winter" },
  { id: "h65", ziel: "suedtirol", name: "Pension Obereggen", kat: "boutique", sterne: 3,
    bau: "small family-run guesthouse of white render and dark wood with a carved balcony",
    ort: "in a South Tyrolean mountain hamlet, apple orchards below", licht: "spring morning, orchards in blossom" },

  // --- Lappland ----------------------------------------------------------
  { id: "h66", ziel: "lappland", name: "Aurora Camp Ivalo", kat: "boutique", sterne: 4,
    bau: "row of small glass-roofed cabins on low timber platforms, warm light inside",
    ort: "in a snow-covered Lapland forest clearing under a dark sky", licht: "polar night with green aurora overhead" },
  { id: "h67", ziel: "lappland", name: "Lodge Kittilä", kat: "berg", sterne: 4,
    bau: "long timber lodge with a low pitched roof, deep eaves heavy with snow, tall chimney",
    ort: "at the edge of a frozen lake in Finnish Lapland", licht: "blue hour in December, snow lit from the windows" },
  { id: "h68", ziel: "lappland", name: "Arctic Glass Suites", kat: "luxus", sterne: 5,
    bau: "modern luxury suites of black timber with fully glazed end walls facing north",
    ort: "on a snow ridge above Finnish Lapland forest", licht: "clear arctic night, stars and faint aurora" },
  { id: "h69", ziel: "lappland", name: "Rentierhof Saariselkä", kat: "familie", sterne: 3,
    bau: "cluster of red-painted wooden Finnish farm buildings with white window frames",
    ort: "in a snowy Lapland clearing, reindeer fences and birch trees", licht: "low pale sun just above the horizon at midday" },

  // --- Ostsee ------------------------------------------------------------
  { id: "h70", ziel: "ostsee", name: "Strandhotel Vitte", kat: "strand", sterne: 4,
    bau: "white German seaside resort building with a veranda, decorative wooden gables and a flag mast",
    ort: "behind the dunes on the German Baltic coast", licht: "bright breezy summer day" },
  { id: "h71", ziel: "ostsee", name: "Gutshaus Boddenblick", kat: "boutique", sterne: 4,
    bau: "restored red brick manor house with a slate roof and a small columned porch",
    ort: "in a park by a Baltic lagoon in northern Germany", licht: "golden autumn afternoon, old trees turning" },
  { id: "h72", ziel: "ostsee", name: "Familienhof Zingst", kat: "familie", sterne: 3,
    bau: "long low family hotel with a reed-thatched roof and white gables",
    ort: "between pine woods and the Baltic dunes", licht: "clear early summer morning" },
  { id: "h73", ziel: "ostsee", name: "Pension Seewind", kat: "budget", sterne: 2,
    bau: "simple two-storey brick guesthouse with white window frames and a small garden gate",
    ort: "in a quiet Baltic seaside village street", licht: "windy overcast day in late autumn" },

  // --- Kreta (Ergänzung) -------------------------------------------------
  { id: "h74", ziel: "kreta", name: "Malia Family Village", kat: "familie", sterne: 4,
    bau: "wide family hotel of white cubic blocks with blue shutters around a central courtyard",
    ort: "behind a long sandy beach on the north coast of Crete", licht: "bright July midday" },
  { id: "h75", ziel: "kreta", name: "Pension Sfakia", kat: "budget", sterne: 2,
    bau: "small plain white guesthouse of two storeys with a simple concrete balcony",
    ort: "in a tiny harbour village on the south coast of Crete, bare mountains behind", licht: "hard sun in late May" },

  // --- Marrakesch --------------------------------------------------------
  { id: "h76", ziel: "marrakesch", name: "Riad Dar Zahra", kat: "boutique", sterne: 4,
    bau: "plain ochre pisé wall with a single carved cedar door, riad hidden behind it",
    ort: "in a narrow medina lane in Marrakesh", licht: "warm low sun in November" },
  { id: "h77", ziel: "marrakesch", name: "Palais Menara", kat: "luxus", sterne: 5,
    bau: "large ochre palace hotel with keyhole arches, zellige detailing and a crenellated parapet",
    ort: "in palm gardens outside Marrakesh with the Atlas mountains snow-capped in the distance", licht: "clear winter morning" },
  { id: "h78", ziel: "marrakesch", name: "Hotel Gueliz", kat: "stadt", sterne: 4,
    bau: "modernist rose-coloured hotel block from the 1960s with horizontal balcony bands",
    ort: "on a boulevard in the new town of Marrakesh, orange trees along the street", licht: "bright dry afternoon in March" },
  { id: "h79", ziel: "marrakesch", name: "Auberge Ourika", kat: "budget", sterne: 2,
    bau: "simple flat-roofed earth-coloured guesthouse with a shaded terrace on the roof",
    ort: "in a village in the Ourika valley below the Atlas mountains", licht: "soft light in the late afternoon" },

  // --- Kapstadt ----------------------------------------------------------
  { id: "h80", ziel: "kapstadt", name: "Table View Lodge", kat: "stadt", sterne: 4,
    bau: "white Cape Dutch style hotel with curved gables and green shutters",
    ort: "in a Cape Town suburb with the flat-topped mountain rising behind", licht: "bright January morning" },
  { id: "h81", ziel: "kapstadt", name: "Vineyard Estate Constantia", kat: "luxus", sterne: 5,
    bau: "long whitewashed wine estate manor with a thatched roof and a colonnaded veranda",
    ort: "among vineyards on a South African hillside", licht: "warm summer evening light" },
  { id: "h82", ziel: "kapstadt", name: "Camps Bay Boutique", kat: "boutique", sterne: 4,
    bau: "crisp modern white boutique hotel of stacked terraces with glass balustrades",
    ort: "on a slope above an Atlantic beach in Cape Town, granite peaks behind", licht: "clear afternoon with strong contrast" },
  { id: "h83", ziel: "kapstadt", name: "Hout Bay Beach", kat: "strand", sterne: 3,
    bau: "relaxed two-storey beach hotel with timber decking and a shaded porch",
    ort: "at a sheltered bay near Cape Town, fishing boats offshore", licht: "hazy morning light" },

  // --- Krabi -------------------------------------------------------------
  { id: "h84", ziel: "krabi", name: "Limestone Bay Resort", kat: "strand", sterne: 4,
    bau: "low resort pavilions with steep tiled roofs and dark timber posts, connected by walkways",
    ort: "on a Thai beach beneath towering limestone karst cliffs", licht: "clear dry-season morning in January" },
  { id: "h85", ziel: "krabi", name: "Ao Nang Sands", kat: "familie", sterne: 4,
    bau: "four-storey family resort in cream render with wide balconies and a tiled hip roof",
    ort: "a street back from a Thai beach promenade, palms all around", licht: "bright midday sun" },
  { id: "h86", ziel: "krabi", name: "Villa Andaman", kat: "luxus", sterne: 5,
    bau: "luxury villa resort of dark teak and white stone, deep overhanging roofs, infinity edge terraces",
    ort: "on a headland above the Andaman Sea in Thailand", licht: "sunset, warm reflections on the water" },
  { id: "h87", ziel: "krabi", name: "Railay Bungalows", kat: "boutique", sterne: 3,
    bau: "simple wooden bungalows on stilts with palm-thatched roofs",
    ort: "in dense jungle at the foot of Thai limestone cliffs", licht: "soft green filtered light after rain" },

  // --- Island ------------------------------------------------------------
  { id: "h88", ziel: "island", name: "Hverfjall Retreat", kat: "boutique", sterne: 4,
    bau: "low black timber hotel with a turf roof and large windows, steam drifting nearby",
    ort: "on a volcanic plain in northern Iceland, snow and steaming ground", licht: "winter twilight, faint aurora" },
  { id: "h89", ziel: "island", name: "Reykjavík Harbour House", kat: "stadt", sterne: 4,
    bau: "corrugated iron clad Icelandic townhouse painted deep red with white window frames",
    ort: "on a harbour street in Reykjavík", licht: "low winter sun, long shadows" },
  { id: "h90", ziel: "island", name: "Glacier View Lodge", kat: "luxus", sterne: 5,
    bau: "modern lodge of dark basalt and floor-to-ceiling glass, single storey, long and low",
    ort: "on a moss plain in southern Iceland facing a glacier tongue", licht: "midnight sun in June, pale gold" },
  { id: "h91", ziel: "island", name: "Guesthouse Vík", kat: "budget", sterne: 2,
    bau: "small white gabled guesthouse with a red roof and a plain porch",
    ort: "in a tiny Icelandic village under a green cliff, black sand beyond", licht: "grey rain-washed light" },

  // --- New York ----------------------------------------------------------
  { id: "h92", ziel: "newyork", name: "Chelsea Brownstone", kat: "boutique", sterne: 4,
    bau: "classic New York brownstone with a high stoop, iron railings and bay windows",
    ort: "on a tree-lined Manhattan side street", licht: "cold December afternoon, bare trees, light snow" },
  { id: "h93", ziel: "newyork", name: "Midtown Tower", kat: "stadt", sterne: 4,
    bau: "slender pre-war Manhattan hotel tower in limestone with setbacks and a stepped crown",
    ort: "between taller towers in midtown Manhattan", licht: "blue hour, windows lit" },
  { id: "h94", ziel: "newyork", name: "The Gramercy Grand", kat: "luxus", sterne: 5,
    bau: "grand red brick and terracotta hotel with a canopied entrance and ornate cornice",
    ort: "facing a small fenced park in Manhattan", licht: "golden autumn afternoon, leaves turning" },
  { id: "h95", ziel: "newyork", name: "Brooklyn Loft Rooms", kat: "budget", sterne: 3,
    bau: "converted brick warehouse with large industrial windows and a plain steel door",
    ort: "in a Brooklyn side street under an elevated road", licht: "flat grey winter light" },

  // --- Kyoto -------------------------------------------------------------
  { id: "h96", ziel: "kyoto", name: "Machiya Gion", kat: "boutique", sterne: 4,
    bau: "traditional Kyoto machiya townhouse of dark timber lattice, tiled roof and a low noren-less entrance",
    ort: "in a narrow stone-paved lane in Kyoto", licht: "soft light in early April, cherry petals on the stones" },
  { id: "h97", ziel: "kyoto", name: "Ryokan Arashiyama", kat: "finca", sterne: 4,
    bau: "low wooden ryokan with deep eaves, sliding screens and a moss garden wall",
    ort: "beside a river below wooded hills in Kyoto", licht: "misty November morning, maples deep red" },
  { id: "h98", ziel: "kyoto", name: "Higashiyama Palace", kat: "luxus", sterne: 5,
    bau: "contemporary luxury hotel of dark timber and pale stone, horizontal roofs, raked gravel forecourt",
    ort: "at the foot of the eastern hills of Kyoto", licht: "clear autumn afternoon" },
  { id: "h99", ziel: "kyoto", name: "Hotel Karasuma", kat: "stadt", sterne: 3,
    bau: "plain modern Japanese business hotel, narrow grey facade with regular small windows",
    ort: "on a busy Kyoto avenue", licht: "overcast spring day" },

  // --- Mallorca (Ergänzung) ----------------------------------------------
  { id: "h100", ziel: "mallorca", name: "Serra Vell Refugi", kat: "boutique", sterne: 4,
    bau: "small stone mountain hotel with green shutters and a terrace on dry stone walls",
    ort: "high in the Tramuntana mountains of Mallorca, terraced olive groves", licht: "cool clear morning in February" },
];
